import {
  Home,
  Briefcase,
  Sparkles,
  GraduationCap,
  Wallet,
  Rocket,
  Compass,
  ShoppingCart,
  ShoppingBag,
  Utensils,
  TrendingUp,
  TrendingDown,
  Zap,
  Heart,
  Plus,
  Wifi,
  Tv,
  Music,
  Bus,
  Car,
  Plane,
  Smartphone,
  Phone,
  Book,
  Film,
  Cloud,
  Layers,
  Building,
  Cpu,
  Megaphone,
  FileText,
  File,
  Shield,
  Target,
  UserPlus,
  Monitor,
  Activity,
  Users,
  PieChart,
  Star,
  Flame,
  Palette,
  Circle,
  Gift,
  Droplets,
  ChartBar,
  BarChart3,
  LineChart,
  PiggyBank,
  Calendar,
  Bell,
  Banknote,
  Fuel,
  AlertCircle,
  ArrowUpRight,
} from 'lucide-react';

/**
 * Resolve an icon by string key. Used by data files to keep records JSON-friendly.
 */
const ICON_MAP = {
  home: Home,
  briefcase: Briefcase,
  sparkles: Sparkles,
  'graduation-cap': GraduationCap,
  wallet: Wallet,
  rocket: Rocket,
  compass: Compass,
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  zap: Zap,
  heart: Heart,
  plus: Plus,
  wifi: Wifi,
  tv: Tv,
  music: Music,
  bus: Bus,
  car: Car,
  plane: Plane,
  smartphone: Smartphone,
  phone: Phone,
  book: Book,
  film: Film,
  cloud: Cloud,
  layers: Layers,
  building: Building,
  cpu: Cpu,
  megaphone: Megaphone,
  'file-text': FileText,
  file: File,
  shield: Shield,
  target: Target,
  'user-plus': UserPlus,
  monitor: Monitor,
  activity: Activity,
  users: Users,
  'pie-chart': PieChart,
  star: Star,
  flame: Flame,
  palette: Palette,
  circle: Circle,
  gift: Gift,
  droplets: Droplets,
  'chart-bar': ChartBar,
  'piggy-bank': PiggyBank,
  calendar: Calendar,
  bell: Bell,
  banknote: Banknote,
  fuel: Fuel,
  'shopping-bag': ShoppingBag,
  'alert-circle': AlertCircle,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-3': BarChart3,
  'line-chart': LineChart,
};

export function getIcon(key, fallback = Circle) {
  return ICON_MAP[key] || fallback;
}

export function CategoryIcon({ name, size = 18, color, bg, className = '' }) {
  const Icon = getIcon(name);
  return (
    <span
      className={`list-icon ${className}`}
      style={{
        background: bg || 'var(--surface-2)',
        color: color || 'var(--text-2)',
        width: 38,
        height: 38,
      }}
    >
      <Icon size={size} strokeWidth={2} />
    </span>
  );
}
